version: "3"
services:
  app:
    build: .
    container_name: "bexs-backend-test"
    restart: "no"
    ports:
      - 3333:3333
    #volumes:
    #  - ./src:/usr/src/app/src
    environment:
      NODE_ENV: "development"
      APP_PORT: 3333
